# Generated by Django 4.1.7 on 2023-04-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(related_name='project', to='projects.category'),
        ),
    ]
