# Generated by Django 4.1.7 on 2023-10-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordlogin', '0002_alter_discorduser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='avatar',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
