# Generated by Django 4.1.7 on 2023-10-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordlogin', '0003_alter_discorduser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='discorduser',
            name='guilds',
            field=models.ManyToManyField(to='discordlogin.guild'),
        ),
        migrations.AddField(
            model_name='discorduser',
            name='roles',
            field=models.ManyToManyField(to='discordlogin.role'),
        ),
    ]
