# Generated by Django 4.1.7 on 2023-10-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordlogin', '0004_guild_role_discorduser_guilds_discorduser_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discorduser',
            name='guilds',
        ),
        migrations.RemoveField(
            model_name='discorduser',
            name='roles',
        ),
        migrations.AddField(
            model_name='discorduser',
            name='discord_guilds',
            field=models.ManyToManyField(related_name='members', to='discordlogin.guild'),
        ),
        migrations.AddField(
            model_name='discorduser',
            name='discord_roles',
            field=models.ManyToManyField(related_name='users', to='discordlogin.role'),
        ),
    ]
