# Generated by Django 4.1.7 on 2023-10-28 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordlogin', '0005_remove_discorduser_guilds_remove_discorduser_roles_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='discorduser',
        #     name='discord_guilds',
        # ),
        # migrations.RemoveField(
        #     model_name='discorduser',
        #     name='discord_roles',
        # ),
        # migrations.DeleteModel(
        #     name='Guild',
        # ),
        # migrations.DeleteModel(
        #     name='Role',
        # ),
    ]
